Release version and type check

diff --git a/.github/workflows/create-branch-from-tag.yml b/.github/workflows/create-branch-from-tag.yml
--- a/.github/workflows/create-branch-from-tag.yml
+++ b/.github/workflows/create-branch-from-tag.yml
@@ -19,6 +19,19 @@ jobs:
           TAG_NAME=${GITHUB_REF#refs/tags/}
           RELEASE_VERSION="${TAG_NAME%%-*}"
           RELEASE_TYPE="${TAG_NAME#*-}"
+
+          if ! [[ $RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid semantic version tag: $RELEASE_VERSION"
+            exit 1
+          fi
+
+          if [[ "$RELEASE_TYPE" =~ refs/tags/(appflow|binary) ]]; then
+          echo "Tag is 'appflow' or 'binary'"
+          exit 0
+          else
+            echo "Error: Tag is not 'appflow' or 'binary'"
+            exit 1
+          fi
         
           echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
